// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ApolloClient__React_Hooks_UseQuery = require("./hooks/ApolloClient__React_Hooks_UseQuery.bs.js");
var ApolloClient__React_Hooks_UseMutation = require("./hooks/ApolloClient__React_Hooks_UseMutation.bs.js");
var ApolloClient__React_Hooks_UseLazyQuery = require("./hooks/ApolloClient__React_Hooks_UseLazyQuery.bs.js");
var ApolloClient__React_Hooks_UseSubscription = require("./hooks/ApolloClient__React_Hooks_UseSubscription.bs.js");

var Context;

var Hooks;

var Types;

var useLazyQuery = ApolloClient__React_Hooks_UseLazyQuery.useLazyQuery;

var useMutation = ApolloClient__React_Hooks_UseMutation.useMutation;

var useQuery = ApolloClient__React_Hooks_UseQuery.useQuery;

var useSubscription = ApolloClient__React_Hooks_UseSubscription.useSubscription;

exports.Context = Context;
exports.Hooks = Hooks;
exports.Types = Types;
exports.useLazyQuery = useLazyQuery;
exports.useMutation = useMutation;
exports.useQuery = useQuery;
exports.useSubscription = useSubscription;
/* ApolloClient__React_Hooks_UseQuery Not a pure module */
