// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Ws = require("@apollo/client/link/ws");
var ApolloClient__SubscriptionsTransportWs = require("../../../../subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.bs.js");

var Js_ = {};

var Configuration = {
  Js_: Js_
};

var Js_$1 = {};

function make(uri, options, webSocketImpl, param) {
  return new Ws.WebSocketLink(({
                NAME: "Configuration",
                VAL: {
                  uri: uri,
                  options: Belt_Option.map(options, ApolloClient__SubscriptionsTransportWs.ClientOptions.toJs),
                  webSocketImpl: webSocketImpl
                }
              }).VAL);
}

function makeWithSubscriptionClient(subscriptionClient) {
  return new Ws.WebSocketLink(subscriptionClient);
}

var WebSocketLink = {
  ClientOptions: undefined,
  SubscriptionClient: undefined,
  Configuration: Configuration,
  Js_: Js_$1,
  make: make,
  makeWithSubscriptionClient: makeWithSubscriptionClient
};

var ApolloLink;

var Graphql;

exports.ApolloLink = ApolloLink;
exports.Graphql = Graphql;
exports.WebSocketLink = WebSocketLink;
/* @apollo/client/link/ws Not a pure module */
