// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Client = require("@apollo/client");

var Js_ = {};

var ReactiveVar = {
  Js_: Js_
};

var Js_$1 = {};

function makeVar(prim) {
  return Client.makeVar(prim);
}

exports.ReactiveVar = ReactiveVar;
exports.Js_ = Js_$1;
exports.makeVar = makeVar;
/* @apollo/client Not a pure module */
