// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Client = require("@apollo/client");

var Js_ = {};

function createHttpLink(prim) {
  return Client.createHttpLink(prim);
}

var ApolloLink;

var HttpOptions;

exports.ApolloLink = ApolloLink;
exports.HttpOptions = HttpOptions;
exports.Js_ = Js_;
exports.createHttpLink = createHttpLink;
/* @apollo/client Not a pure module */
