// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Js_ = {};

var UriFunction = {
  Js_: Js_
};

var Js_$1 = {};

var HttpOptions = {
  Js_: Js_$1
};

var Operation;

exports.Operation = Operation;
exports.UriFunction = UriFunction;
exports.HttpOptions = HttpOptions;
/* No side effect */
