// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Client = require("@apollo/client");

var Js_ = {};

function make(uri, includeExtensions, $$fetch, headers, credentials, fetchOptions, useGETForQueries, param) {
  return new Client.HttpLink({
              uri: uri,
              includeExtensions: includeExtensions,
              fetch: $$fetch,
              headers: headers,
              credentials: credentials,
              fetchOptions: fetchOptions,
              useGETForQueries: useGETForQueries
            });
}

var ApolloLink;

var HttpOptions;

var UriFunction;

exports.ApolloLink = ApolloLink;
exports.HttpOptions = HttpOptions;
exports.UriFunction = UriFunction;
exports.Js_ = Js_;
exports.make = make;
/* @apollo/client Not a pure module */
