// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ASTNode = {};

var _map = {"SOF":"SOF","EOF":"EOF","BANG":"BANG","DOLLAR":"DOLLAR","AMP":"AMP","PAREN_L":"PAREN_L","PAREN_R":"PAREN_R","SPREAD":"SPREAD","COLON":"COLON","EQUALS":"EQUALS","AT":"AT","BRACKET_L":"BRACKET_L","BRACKET_R":"BRACKET_R","BRACE_L":"BRACE_L","PIPE":"PIPE","BRACE_R":"BRACE_R","NAME":"NAME","INT":"INT","FLOAT":"FLOAT","STRING":"STRING","BLOCK_STRING":"BLOCK_STRING","COMMENT":"COMMENT"};

function tToJs(param) {
  return param;
}

function tFromJs(param) {
  return _map[param];
}

var TokenKindEnum = {
  tToJs: tToJs,
  tFromJs: tFromJs
};

var Token = {};

var $$Location = {};

var NameNode = {};

var NamedTypeNode = {};

var ValueNode = {};

var ArgumentNode = {};

var DirectiveNode = {};

var SelectionNode = {};

var SelectionSetNode = {};

var FieldNode = {};

var FragmentDefinitionNode = {};

var VariableNode = {};

var VariableDefinitionNode = {};

var OperationTypeNode = {};

var OperationDefinitionNode = {};

var Source;

exports.ASTNode = ASTNode;
exports.Source = Source;
exports.TokenKindEnum = TokenKindEnum;
exports.Token = Token;
exports.$$Location = $$Location;
exports.NameNode = NameNode;
exports.NamedTypeNode = NamedTypeNode;
exports.ValueNode = ValueNode;
exports.ArgumentNode = ArgumentNode;
exports.DirectiveNode = DirectiveNode;
exports.SelectionNode = SelectionNode;
exports.SelectionSetNode = SelectionSetNode;
exports.FieldNode = FieldNode;
exports.FragmentDefinitionNode = FragmentDefinitionNode;
exports.VariableNode = VariableNode;
exports.VariableDefinitionNode = VariableDefinitionNode;
exports.OperationTypeNode = OperationTypeNode;
exports.OperationDefinitionNode = OperationDefinitionNode;
/* No side effect */
