// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Js_ = {};

var FragmentMatcher = {
  Js_: Js_
};

var Js_$1 = {};

var Resolver = {
  Js_: Js_$1
};

var ApolloCache;

var FieldNode;

var FragmentMap;

exports.ApolloCache = ApolloCache;
exports.FieldNode = FieldNode;
exports.FragmentMap = FragmentMap;
exports.FragmentMatcher = FragmentMatcher;
exports.Resolver = Resolver;
/* No side effect */
