// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ApolloClient;

var LocalState;

var NetworkStatus;

var ObservableQuery;

var Types;

var WatchQueryOptions;

exports.ApolloClient = ApolloClient;
exports.LocalState = LocalState;
exports.NetworkStatus = NetworkStatus;
exports.ObservableQuery = ObservableQuery;
exports.Types = Types;
exports.WatchQueryOptions = WatchQueryOptions;
/* No side effect */
