// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");
var Utilities = require("@apollo/client/utilities");
var ApolloClient__Cache_InMemory_Policies_FieldPolicy = require("../../cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.bs.js");

var Js_ = {};

function concatPagination(keyArgs) {
  return Utilities.concatPagination(Caml_option.some(ApolloClient__Cache_InMemory_Policies_FieldPolicy.FieldPolicy_KeyArgs.toJs(keyArgs)));
}

function offsetLimitPagination(keyArgs) {
  return Utilities.offsetLimitPagination(Caml_option.some(ApolloClient__Cache_InMemory_Policies_FieldPolicy.FieldPolicy_KeyArgs.toJs(keyArgs)));
}

function relayStylePagination(keyArgs) {
  return Utilities.relayStylePagination(Caml_option.some(ApolloClient__Cache_InMemory_Policies_FieldPolicy.FieldPolicy_KeyArgs.toJs(keyArgs)));
}

var FieldPolicy;

var KeyArgs;

exports.FieldPolicy = FieldPolicy;
exports.KeyArgs = KeyArgs;
exports.Js_ = Js_;
exports.concatPagination = concatPagination;
exports.offsetLimitPagination = offsetLimitPagination;
exports.relayStylePagination = relayStylePagination;
/* @apollo/client/utilities Not a pure module */
