// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var UseApolloClient;

var UseMutation;

var UseQuery;

var UseSubscription;

exports.UseApolloClient = UseApolloClient;
exports.UseMutation = UseMutation;
exports.UseQuery = UseQuery;
exports.UseSubscription = UseSubscription;
/* No side effect */
