// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ApolloClient__Link_Core_Types = require("../core/ApolloClient__Link_Core_Types.bs.js");

var Js_ = {};

function toJs(t, count, operation, error) {
  return Curry._3(t, count, ApolloClient__Link_Core_Types.Operation.fromJs(operation), error);
}

var DelayFunction = {
  Js_: Js_,
  toJs: toJs
};

var Js_$1 = {};

var DelayFunctionOptions = {
  Js_: Js_$1
};

var Operation;

exports.Operation = Operation;
exports.DelayFunction = DelayFunction;
exports.DelayFunctionOptions = DelayFunctionOptions;
/* ApolloClient__Link_Core_Types Not a pure module */
