// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ApolloClient__Link_Core_Types = require("../core/ApolloClient__Link_Core_Types.bs.js");

var Js_ = {};

function toJs(t, count, operation, error) {
  return Curry._3(t, count, ApolloClient__Link_Core_Types.Operation.fromJs(operation), error);
}

var RetryFunction = {
  Js_: Js_,
  toJs: toJs
};

var Js_$1 = {};

function toJs$1(t) {
  return {
          max: t.max,
          retryIf: (function (error, operation) {
              return Curry._2(t.retryIf, error, ApolloClient__Link_Core_Types.Operation.fromJs(operation));
            })
        };
}

var RetryFunctionOptions = {
  Js_: Js_$1,
  toJs: toJs$1
};

var Operation;

exports.Operation = Operation;
exports.RetryFunction = RetryFunction;
exports.RetryFunctionOptions = RetryFunctionOptions;
/* ApolloClient__Link_Core_Types Not a pure module */
