// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Js_ = {};

var ExecutionResult = {
  Js_: Js_
};

var GraphQLError;

exports.GraphQLError = GraphQLError;
exports.ExecutionResult = ExecutionResult;
/* No side effect */
