// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Js_ = {};

var CanReadFunction = {
  Js_: Js_
};

var Js_$1 = {};

var ReadFieldFunction = {
  Js_: Js_$1
};

var Js_$2 = {};

var ToReferenceFunction = {
  Js_: Js_$2
};

var StoreValue;

exports.StoreValue = StoreValue;
exports.CanReadFunction = CanReadFunction;
exports.ReadFieldFunction = ReadFieldFunction;
exports.ToReferenceFunction = ToReferenceFunction;
/* No side effect */
