// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Js_ = {};

var FragmentMap = {
  Js_: Js_
};

var FragmentDefinitionNode;

exports.FragmentDefinitionNode = FragmentDefinitionNode;
exports.FragmentMap = FragmentMap;
/* No side effect */
