// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ReasonMLCommunity__ApolloClient = require("./ReasonMLCommunity__ApolloClient.bs.js");

var make = ReasonMLCommunity__ApolloClient.make;

var DefaultWatchQueryOptions = ReasonMLCommunity__ApolloClient.DefaultWatchQueryOptions;

var DefaultQueryOptions = ReasonMLCommunity__ApolloClient.DefaultQueryOptions;

var DefaultMutateOptions = ReasonMLCommunity__ApolloClient.DefaultMutateOptions;

var DefaultOptions = ReasonMLCommunity__ApolloClient.DefaultOptions;

var React = ReasonMLCommunity__ApolloClient.React;

var Cache = ReasonMLCommunity__ApolloClient.Cache;

var Link = ReasonMLCommunity__ApolloClient.Link;

var Utilities = ReasonMLCommunity__ApolloClient.Utilities;

var Bindings = ReasonMLCommunity__ApolloClient.Bindings;

var GraphQL_PPX = ReasonMLCommunity__ApolloClient.GraphQL_PPX;

var Types = ReasonMLCommunity__ApolloClient.Types;

exports.make = make;
exports.DefaultWatchQueryOptions = DefaultWatchQueryOptions;
exports.DefaultQueryOptions = DefaultQueryOptions;
exports.DefaultMutateOptions = DefaultMutateOptions;
exports.DefaultOptions = DefaultOptions;
exports.React = React;
exports.Cache = Cache;
exports.Link = Link;
exports.Utilities = Utilities;
exports.Bindings = Bindings;
exports.GraphQL_PPX = GraphQL_PPX;
exports.Types = Types;
/* ReasonMLCommunity__ApolloClient Not a pure module */
