// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utilities = require("@apollo/client/utilities");

function getOperationDefinition(prim) {
  return Utilities.getOperationDefinition(prim);
}

var Graphql;

var Observables;

var Policies;

exports.getOperationDefinition = getOperationDefinition;
exports.Graphql = Graphql;
exports.Observables = Observables;
exports.Policies = Policies;
/* @apollo/client/utilities Not a pure module */
